config/routes.rb
Rails.application.routes.draw do  
  resources :dimensions
  resources :goals
  resources :message_categories
  resources :messages, except: [:index, :destroy] do
    collection do
      get :sent_messages
      get :received_messages
    end
  end

  resources :posts
  devise_for :users, :controllers => {sessions: 'sessions', registrations: 'registrations'} 
  resources :employees do
    resources :dimensions
    resources :goals
    collection do
      post :search
      get :my_profile
    end
    member do 
      get :linked_in_profile
    end
    resources :users, only: [:new, :create, :edit, :update, :destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :job_titles
  resources :roles, only: [:index] do
    resources :dimensions
  end
  resources :companies do 
    resources :dimensions
    resources :goals
    resources :business_units do      
      resources :departments do
        resources :teams
      end
    end
  end

  resources :business_units do
    resources :dimensions
  end

  resources :teams do
    resources :dimensions
    resources :goals
  end

  resources :chat_rooms do
    member do
      delete :leave
    end
    # resources :chat_room_members, path: :members
    resources :chat_messages do
      collection do
        delete :clear_chat_history, to: "chat_messages#clear_chat_history"
      end
    end
  end


  mount ActionCable.server => '/cable'

  
  root to: "home#index"

  get '/api' => redirect('/swagger/dist/index.html?url=/apidocs/api-docs.json')

end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
	attr_accessor :target_employee

  	belongs_to :created_by, class_name: Employee, foreign_key: :employee_id
  	
  	has_many :chat_room_members, dependent: :destroy
  	has_many :members, through: :chat_room_members ,class_name: Employee, foreign_key: :employee_id, :source => :employee

  	has_many :chat_messages, dependent: :destroy

  	validates :title, :uniqueness => true

  	after_create :create_members

    accepts_nested_attributes_for :members

  	private
  	def create_members
  		chat_room_members.create(employee_id: created_by.id)
  	end
end

app/models/employee.rb
# Employee Model
class Employee < ApplicationRecord
  attr_accessor :primary_skills_params, :secondary_skills_params,
                :interests_params

  has_one :user
  belongs_to :business_unit

  belongs_to :reports_to_manager, :class_name => 'Employee', :foreign_key => 'reports_to'
  has_many :reportees, class_name: 'Employee', :foreign_key => "reports_to"

  has_many :employee_departments
  has_many :departments, through: :employee_departments

  has_many :employee_teams
  has_many :teams, through: :employee_teams

  has_many :employee_skills
  has_many :skills, through: :employee_skills

  has_many :primary_skills, -> { where('employee_skills.is_primary is true') }, through: :employee_skills, source: :skill
  has_many :secondary_skills, -> { where('employee_skills.is_primary is not true') }, through: :employee_skills, source: :skill

  has_many :employee_interests
  has_many :interests, through: :employee_interests

  # has_many :chat_rooms, dependent: :destroy
  has_many :created_chat_rooms, class_name: ChatRoom, foreign_key: :employee_id
  has_many :chat_messages, dependent: :destroy

  has_many :chat_room_members
  has_many :chat_rooms, through: :chat_room_members

  belongs_to :job_title
  has_many :dimensions, as: :reference
  has_many :goals, as: :reference

	has_many :sent_messages, class_name: 'Message', foreign_key: :sender_id
	has_many :received_messages, class_name: 'Message', foreign_key: :recipient_id

	has_many :received_anonymous_messages, -> { where("messages.anonymous is true")}, class_name: 'Message', foreign_key: :recipient_id
	has_many :received_nonanonymous_messages, -> { where("messages.anonymous is false")}, class_name: 'Message', foreign_key: :recipient_id
	



  
	validates :first_name, :date_of_birth, :employee_code, :joining_date, :mobile, :gender, :presence => true
	validates :employee_code, :mobile , uniqueness: true

  has_attached_file :photo, styles: { small: '40x40#', medium: '80x80#', large: '160x160#' }, default_url: '/images/missing_:style.png'
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/

  accepts_nested_attributes_for :employee_departments
  accepts_nested_attributes_for :employee_teams
  accepts_nested_attributes_for :interests

  def full_name
    [first_name.try(:capitalize), middle_name.try(:capitalize), last_name.try(:capitalize)].reject {|n| n.blank? }.join(" ")	
  end

  private

  def self.search(params)
    include_models = []
    where_condition = {}

    query = params[:business_unit]
    unless query.blank?
      include_models << [:business_unit]
      where_condition.merge!({ business_units: { title: query } })
    end

    query = params[:business_unit_ids]
    unless query.blank?
      raise 'Invalid request object, business_unit_ids should be an array' unless query.is_a?(Array)
      include_models << [:business_unit]
      where_condition.merge!({ business_units: { id: query } })
    end

    query = params[:departments]
    unless query.blank?
      include_models << [:employee_departments, :departments]
      where_condition.merge!({ departments: { title: query } })
    end

    query = params[:department_ids]
    unless query.blank?
      raise 'Invalid request object, department_ids should be an array' unless query.is_a?(Array)
      include_models << [:employee_departments, :departments]
      where_condition.merge!({ departments: { id: query } })
    end

    query = params[:teams]
    unless query.blank?
      include_models << [:employee_teams, :teams]
      where_condition.merge!({ teams: { title: query } })
    end

    query = params[:team_ids]
    unless query.blank?
      raise 'Invalid request object, team_ids should be an array' unless query.is_a?(Array)
      include_models << [:employee_teams, :teams]
      where_condition.merge!({ teams: { id: query } })
    end

    query = params[:skills]
    unless query.blank?
      include_models << [:employee_skills, :skills]
      where_condition.merge!({ skills: { title: query } })
    end

    query = params[:interests]
    unless query.blank?
      include_models << [:employee_interests, :interests]
      where_condition.merge!({ interests: { title: query } })
    end
    include_models.uniq!
    query = params[:name]
    if query.blank?
      Employee.includes(include_models).where(where_condition)
    else
      Employee.includes(include_models).where(where_condition).where("first_name ILIKE ? OR last_name ILIKE ? OR middle_name ILIKE ? ", "%#{query}%", "%#{query}%", "%#{query}%")
    end
  end
end

app/controllers/employees_controller.rb
#TODOs
## soft delete
## All employees API


class EmployeesController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource 

  swagger_controller :employees, "Employees Management"

  swagger_api :index do
    summary "Employees Directory"
    param :query, :alphabet, :string, :optional, "Alphabet ehich need to be sorted"
  end

  swagger_api :create do
    summary "Creates a new Employee"
    param :form, "employee[first_name]", :string, :required
    param :form, "employee[middle_name]", :string, :optional
    param :form, "employee[last_name]", :string, :optional
    param_list :form, "employee[gender]", :string, :optional, "Gender", [ "Male", "Female" ]

    param :form, "employee[date_of_birth]", :string, :required
    param :form, "employee[employee_code]", :string, :required
    param :form, "employee[mobile]", :string, :required
    param_list :form, "employee[job_title_id]", :string, :optional,"Gender", JobTitle.all.map(&:id)
    param_list :form, "freq", :string, :optional, "Frequency", ["daily", "monthly", "monthly"]

    param :form, "employee[about]", :file, :optional

    param :form, "employee[address_line_1]", :string, :required, "Address Line one"
    param :form, "employee[address_line_2]", :string, :optional, "Address Line one"
    param :form, "employee[city]", :string, :required, "City"
    param :form, "employee[state]", :string, :optional, "State"
    param :form, "employee[zip]", :string, :optional, "Zipcode"
    param :form, "employee[country]", :string, :required, "Country"
    param :form, "employee[phone]", :string, :optional, "Phone"   
    param :form, "employee[fax]", :string, :optional, "Fax"   
    param :form, "employee[url]", :string, :optional, "Url"

    response :unauthorized
    response :not_acceptable
  end
  
  swagger_api :update do
    summary "Update Employee"
    param :form, "employee[first_name]", :string, :required
    param :form, "employee[middle_name]", :string, :optional
    param :form, "employee[last_name]", :string, :optional
    param_list :form, "employee[gender]", :string, :required,"Gender", [ "Male", "Female" ]

    param :form, "employee[date_of_birth]", :string, :required
    param :form, "employee[employee_code]", :string, :required
    param :form, "employee[mobile]", :string, :required
    param_list :form, "employee[job_title_id]", :string, :required,"Gender", JobTitle.all.map(&:id)
    param :form, "employee[about]", :file, :optional

    param :form, "employee[address_line_1]", :string, :required, "Address Line one"
    param :form, "employee[address_line_2]", :string, :optional, "Address Line one"
    param :form, "employee[city]", :string, :required, "City"
    param :form, "employee[state]", :string, :optional, "State"
    param :form, "employee[zip]", :string, :optional, "Zipcode"
    param :form, "employee[country]", :string, :required, "Country"
    param :form, "employee[phone]", :string, :optional, "Phone"   
    param :form, "employee[fax]", :string, :optional, "Fax"   
    param :form, "employee[url]", :string, :optional, "Url"
    
    response :unauthorized
    response :not_acceptable
  end

  def index
    @employees = Employee.all
    alphabet = params[:alphabet].try(:downcase) || "a"
    if params[:search]
      @employees = Employee.search(params[:search]).order("employee_id ASC")
    else
      @employees = Employee.where('lower(substr(first_name, 1, 1)) = ?', alphabet).order("employee_code ASC")
    end
    @count = @employees.count
    @total_count = Employee.count

    respond_to do |format|
      format.html # show.html.erb
      format.json #{ render json: @people}
     end    
  end

  def show
  end

  def my_profile
    @employee = current_employee
    respond_to do |format|
      format.html 
      format.json { render :show }
    end    
  end

  # GET /employees/new
  def new
    @employee = Employee.new
    @employee_departments = @employee.employee_departments.build(employee_params)
    @employee_departments = @employee.employee_teams.build(employee_params)
  end

  # GET /employees/1/edit
  def edit
  end

  def create
    @employee = Employee.new(employee_params().merge({created_by: current_user.id, updated_by: current_user.id}))
    ActiveRecord::Base.transaction do
      @employee.save!
      update_employee_skills()
      respond_to do |format|
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :ok, location: @employee }
      end
    end
    rescue ActiveRecord::RecordInvalid => e 
    respond_to do |format|
      format.html { render :new }
      format.json { render json: generate_error(:bad_request, e.message), status: :unprocessable_entity }
    end
  end

  def update
    ActiveRecord::Base.transaction do
      @employee.update!(employee_params().merge({created_by: current_user.id, updated_by: current_user.id}))
      update_employee_skills()
      update_employee_interest()
      respond_to do |format|
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      end
    end
    rescue ActiveRecord::RecordInvalid => e 
    respond_to do |format|
      format.html { render :edit }
      format.json { render json: generate_error(:bad_request, e.message), status: :unprocessable_entity }
    end
  end

  def update_employee_skills
    primary_skills, secondary_skills = [], []
    #Both will be in form of array of string, i.e [Ruby, Angular JS]

    primary_skills = params[:employee][:primary_skills_params]

    unless primary_skills.blank?
      @employee.primary_skills.destroy_all
      primary_skills = primary_skills.collect{|s| {title: s}}

      primary_skills.each do |p_s|
        p_skill = Skill.find_or_create_by(p_s)
        p_skills = @employee.employee_skills.build({is_primary: true, skill_id: p_skill.try(:id)})
        p_skills.save
      end      
    end

    secondary_skills = params[:employee][:secondary_skills_params]

    unless secondary_skills.blank?
      @employee.secondary_skills.destroy_all
      secondary_skills = secondary_skills.collect{|s| {title: s}}
      
      secondary_skills.each do |p_s|
        p_skill = Skill.find_or_create_by(p_s)
        p_skills = @employee.employee_skills.build({skill_id: p_skill.try(:id)})
        p_skills.save
      end      
    end
  end

  def update_employee_interest
    interests = []
    #Both will be in form of array of string, i.e [Ruby, Angular JS]
    interests = params[:employee][:interests]

    return if interests.blank?

    interests = interests.collect{|s| {title: s}}
    

    @employee.interests.destroy_all
    @employee.reload

    interests.each do |interest|
      t_int = Interest.find_or_create_by(interest)
      t_ints = @employee.employee_interests.build({interest_id: t_int.try(:id)})
      t_ints.save
    end

  end

  def search
    begin
      @employees = Employee.search(params[:search])   
    rescue Exception => e
      render json: generate_error(:invalid_employee_search_request, e.message)
    end
  end

  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      if can? :create, Employee
        params.fetch(:employee, {}).permit(:first_name, :middle_name, :last_name, :gender, :date_of_birth, :marital_status, :employee_code, :joining_date, :mobile, :office_phone, :office_phone_ext, :address_line_1, :address_line_2, :city, :state, :zip, :country, :about, :linked_url, :github_url, :facebook_url, :blog_url, :other_references, :job_title_id, :reports_to, :is_active, :user_id, :business_unit_id, :photo, employee_departments_attributes: [:department_id, :is_department_head], employee_teams_attributes: [:team_id], primary_skills_params: [:title, :is_primary], secondary_skills_params: [:title], interests_params: [:title] )
      else
        params.fetch(:employee, {}).permit(:first_name, :middle_name, :last_name, :marital_status, :mobile, :address_line_1, :address_line_2, :city, :state, :zip, :country, :about, :linked_url, :github_url, :facebook_url, :blog_url, :other_references, :photo, primary_skills_params: [:title, :is_primary], secondary_skills_params: [:title], interests_params: [:title] )        
      end
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_for employee, :html => { :multipart => true, :class => 'form-horizontal'}  do |f| %>
  <div class="col-md-6 col-sm-12 col-xs-12">

    <div class="form-group">
      <label class="col-lg-3 control-label">First Name<span class="required">*</span></label>
      <div class="col-lg-9">
        <%= f.text_field :first_name, :class => 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label "Middle Name", :class => 'col-lg-3 control-label' %>
      <div class="col-lg-9">
        <%= f.text_field :middle_name, :class => 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label "Last Name", :class => 'col-lg-3 control-label' %>
      <div class="col-lg-9">
        <%= f.text_field :last_name, :class => 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label "Profile Review", :class => 'control-label col-lg-3 control-label' %>
      <div class="col-lg-9">
        <div class="radio">
          <label>
          <%= f.radio_button :gender, "Male", required: true%>Male
          </label>
          <label>
            <%= f.radio_button :gender, "Female", required: true %>Female
          </label>
        </div>
      </div>
    </div> 

    <div class="form-group has-feedback">
      <%= f.label "Date of Birth", :class => 'col-lg-3 control-label' %>
      <div class="col-lg-9">
        <%= f.text_field :date_of_birth, :class => 'form-control has-feedback-left' %>
        <span class="fa fa-calendar form-control-feedback left" aria-hidden="true"></span>
      </div>
    </div>

    <div class="form-group">
      <%= f.label "Marital Status", :class => 'control-label col-lg-3 control-label' %>
      <div class="col-lg-9">
        <div class="radio">
          <label>
          <%= f.radio_button :marital_status, "Single", required: true%>Single
          </label>
          <label>
            <%= f.radio_button :marital_status, "Married", required: true %>Married
          </label>
        </div>
      </div>
    </div> 

    <div class="form-group">
      <%= f.label "Photo", :class => 'col-lg-3 control-label' %>
      <div class="col-lg-9">
        <%= f.file_field :photo, :class => 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label "Linkedin URL", :class => 'col-lg-3 control-label' %>
      <div class="col-lg-9">
        <%= f.text_field :linked_url, :class => 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label "Github URL", :class => 'col-lg-3 control-label' %>
      <div class="col-lg-9">
        <%= f.text_field :github_url, :class => 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label "Facebook URL", :class => 'col-lg-3 control-label' %>
      <div class="col-lg-9">
        <%= f.text_field :facebook_url, :class => 'form-control' %>
      </div>
    </div> 

    <div class="form-group">
      <%= f.label "Blog URL", :class => 'col-lg-3 control-label' %>
      <div class="col-lg-9">
        <%= f.text_field :blog_url, :class => 'form-control' %>
      </div>
    </div> 

    <div class="form-group">
      <%= f.label "Other Refernce", :class => 'col-lg-3 control-label' %>
      <div class="col-lg-9">
        <%= f.text_field :other_references, :class => 'form-control' %>
      </div>
    </div>     
  </div>

  <div class="col-md-6 col-sm-12 col-xs-12">

    <div class="form-group">
      <label class="col-lg-3 control-label">Job Title<span class="required">*</span></label>
      <div class="col-lg-9">
        <%= f.collection_select :job_title_id, JobTitle.all, :id, :title, { :include_blank => "Select Job Title" }, { :class => 'form-control' } %>
      </div>
    </div> 

    <div class="form-group">
      <label class="col-lg-3 control-label">Job Location<span class="required">*</span></label>
      <div class="col-lg-9">
        <%= f.collection_select :business_unit_id, BusinessUnit.all, :id, :title, { :include_blank => "Select Job Title" }, { :class => 'form-control', onchange: "return loadDepartments();" } %>
      </div>
    </div> 

    <%= f.fields_for :employee_departments do |ep| %>
      <div class="form-group">
        <label class="col-lg-3 control-label">Departments<span class="required">*</span></label>
        <div class="col-lg-9">
          <%= ep.collection_select :department_id, Department.all, :id, :title, { :include_blank => "Select Job Title" }, { :class => 'form-control', required: "required" } %>
        </div>
      </div> 

      <div class="form-group">
        <%= f.label "Is Department head", :class => 'col-lg-3 control-label' %>
        <div class="col-lg-9">
          <div class="checkbox">
            <label>
              <%= ep.check_box :is_department_head, {}%>
            </label>
          </div>
        </div>
      </div>      
    <%end%>

    <%= f.fields_for :employee_teams do |et| %>
      <div class="form-group">
        <label class="col-lg-3 control-label">Team<span class="required">*</span></label>
        <div class="col-lg-9">
          <%= et.collection_select :team_id, Team.all, :id, :title, { :include_blank => "Select Job Title" }, { :class => 'form-control', required: "required" } %>
        </div>
      </div>      
    <%end%>

    <div class="form-group">
      <label class="col-lg-3 control-label">Employee ID<span class="required">*</span></label>
      <div class="col-lg-9">
        <%= f.text_field :employee_code, :class => 'form-control' %>
      </div>
    </div>  

    <div class="form-group has-feedback">
      <%= f.label "Joining Date", :class => 'col-lg-3 control-label' %>
      <div class="col-lg-9">
        <%= f.text_field :joining_date, :class => 'form-control has-feedback-left' %>
        <span class="fa fa-calendar form-control-feedback left" aria-hidden="true"></span>
      </div>
    </div>

    <div class="form-group">
      <label class="col-lg-3 control-label">Address Line 1<span class="required">*</span></label>
      <div class="col-lg-9">
        <%= f.text_field :address_line_1, :class => 'form-control' %>
      </div>
    </div>  

    <div class="form-group">
      <%= f.label "Address Line 2", :class => 'control-label col-lg-3 control-label' %>
      <div class="col-lg-9">
        <%= f.text_field :address_line_2, :class => 'form-control' %>
      </div>
    </div>  

    <div class="form-group">
      <%= f.label "City & State", :class => 'control-label col-lg-3 control-label' %>
      <div class="col-lg-4">
        <%= f.text_field :city, :class => 'form-control', placeholder: "City" %>
      </div>
      <div class="col-lg-5">
        <%= f.text_field :state, :class => 'form-control', placeholder: "State" %>
      </div>
    </div>  

    <div class="form-group">
      <%= f.label "Country & Zip code", :class => 'control-label col-lg-3 control-label' %>
      <div class="col-lg-5">
        <%= f.text_field :country, :class => 'form-control' %>
      </div>
      <div class="col-lg-4">
        <%= f.text_field :zip, :class => 'form-control', placeholder: "Zip code" %>
      </div>      
    </div>  

    <div class="form-group">
      <%= f.label "Contact info", :class => 'control-label col-lg-3 control-label' %>
      <div class="col-lg-5">
        <%= f.text_field :office_phone_ext, :class => 'form-control' %>
      </div>
      <div class="col-lg-4">
        <%= f.text_field :office_phone, :class => 'form-control', placeholder: "Home Phone Number" %>
      </div>      
    </div>   

    <div class="form-group">
      <%= f.label "Office Phone", :class => 'control-label col-lg-3 control-label' %>
      <div class="col-lg-9">
        <%= f.text_field :mobile, :class => 'form-control', placeholder: "Mobile" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label "Is Active", :class => 'col-lg-3 control-label' %>
      <div class="col-lg-9">
        <div class="checkbox">
          <label>
            <%= f.check_box :is_active, {}%>
          </label>
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= f.label "About", :class => 'control-label col-lg-3 control-label' %>
      <div class="col-lg-9">
        <%= f.text_area :about, :class => 'form-control', placeholder: "Brief introduction about Employee" %>
      </div>
    </div>

  </div>

  <div class="clearfix"></div>

  <div class="ln_solid"></div>

  <div class="form-group">

    <div class="col-md-12">
    <%= button_tag(:type => "submit", :class => "btn btn-success pull-right") do %>
      <span class="fa fa-save fa-fw"></span> Save
    <% end %>

    <%= link_to employees_path(), :class => 'btn btn-danger'  do %>
      <span class="fa fa-ban fa-fw"></span> Cancel
    <% end %>         
  </div>
</div>

<% end %>


<script type="text/javascript">
  function loadDepartments(){
    $.getJSON("/companies/1/business_units/1/departments.json", function(departments){
      console.log(departments);

$.each(departments, function(index, value) {
  console.log(value.id);
      $('#employee_employee_departments_attributes_0_department_id option[value="'+value.id+'"]').remove();
});


      // $('#employee_employee_departments_attributes_0_department_id option[value!="3"]').remove();
    })
    // $('#employee_employee_departments_attributes_0_department_id option[value!="3"]').remove();
  }
</script>>

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<div class="row">
  <div class="col-md-12 col-sm-6 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2>Employees <small> </small></h2>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12 text-center">
              <ul class="pagination pagination-split">
            <%("A".."Z").each do |alphabet|%>
              <li>
                  <%= link_to alphabet ,employees_path(alphabet: alphabet), class: (alphabet == params[:alphabet].try(:upcase) ? "selected" : "")%>
              </li>
            <%end%>
              </ul>
            </div>

            <div class="clearfix"></div>

            <table class="table">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Name</th>
                  <th>Code</th>
                  <th>Department & Team</th>
                  <th>Chat</th>
                  <th>Mobile</th>
                  <th>Email/username</th>
                  <th></th>  
                </tr>
              </thead>
              <tbody>
                <% @employees.each_with_index do |emp, index| %>
                  <tr>
                    <td><%= index + 1%> </td>
                    <td><%= emp.full_name%> (<%= emp.job_title.try(:title)%>)</td>
                    <td><%= emp.employee_code%></td>
                    <td> TBD </td>
                    <td><%= emp.mobile%></td>
                    <td><%= emp.user.try(:email)%></td>
                    <td><%= link_to "Chat", chat_rooms_path("chat_room[member_ids]": [emp.id]), method: :post%></td>
                    <td><%= link_to 'Edit', edit_employee_path(emp) %></td>
                    <td><%= link_to 'Destroy', emp, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                  </tr>
                <% end %>                        
              </tbody>
            </table>
          </div>
        

        </div>
    </div>
  </div>
  <%= link_to "Add New Employee", new_employee_path(), class: "btn btn-primary pull-right"%>
</div>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>