config/routes.rb
Rails.application.routes.draw do  
  resources :dimensions
  resources :goals
  resources :message_categories
  resources :messages, except: [:index, :destroy] do
    collection do
      get :sent_messages
      get :received_messages
    end
  end

  resources :posts
  devise_for :users, :controllers => {sessions: 'sessions', registrations: 'registrations'} 
  resources :employees do
    resources :dimensions
    resources :goals
    collection do
      post :search
      get :my_profile
    end
    member do 
      get :linked_in_profile
    end
    resources :users, only: [:new, :create, :edit, :update, :destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :job_titles
  resources :roles, only: [:index] do
    resources :dimensions
  end
  resources :companies do 
    resources :dimensions
    resources :goals
    resources :business_units do      
      resources :departments do
        resources :teams
      end
    end
  end

  resources :business_units do
    resources :dimensions
  end

  resources :teams do
    resources :dimensions
    resources :goals
  end

  resources :chat_rooms do
    member do
      delete :leave
    end
    # resources :chat_room_members, path: :members
    resources :chat_messages do
      collection do
        delete :clear_chat_history, to: "chat_messages#clear_chat_history"
      end
    end
  end


  mount ActionCable.server => '/cable'

  
  root to: "home#index"

  get '/api' => redirect('/swagger/dist/index.html?url=/apidocs/api-docs.json')

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		if current_user.try(:admin?) && Company.first.nil?
			redirect_to new_company_path()
		end

		@company = Company.first
	end
	
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_admin_dashboard.html.erb
<!-- Title -->
<div class="row">
    <div class="col-lg-12">
        <h3>Configurations</h3>
    </div>
</div>
<!-- /.row -->
<div class="row text-center">
    <%if can?(:read, Company)%>
    <div class="col-md-3 col-sm-6 hero-feature">
        <div class="thumbnail">
            <h2>Company</h2>
            <div class="caption">
                <h3><%= @company.try(:name) || "Setup Company Profile"%></h3>
                <p>
                    <%if @company.nil?%>
                        <%= link_to "Add", new_company_path(), class: "btn btn-primary"%>
                    <%else%>
                        <%= link_to "Change", edit_company_path(@company), class: "btn btn-primary"%>
                    <%end%>
                </p>
            </div>
        </div>
    </div>
    <%end%>

    <%if can?(:read, JobTitle)%>
    <div class="col-md-3 col-sm-6 hero-feature">
        <div class="thumbnail">
            <h2>Job Title</h2>
            <div class="caption">
                <h3>Setup Job Title</h3>
                <p>
                    <%= link_to "List", job_titles_path(), class: "btn btn-primary"%>
                </p>
            </div>
        </div>
    </div>
    <%end%>

    <%if can?(:manage, Role)%>
    <div class="col-md-3 col-sm-6 hero-feature">
        <div class="thumbnail">
            <h2>User Roles</h2>
            <div class="caption">
                <h3>Setup User Roles</h3>
                <p>
                    <%= link_to "List", roles_path(), class: "btn btn-primary"%>
                </p>
            </div>
        </div>
    </div>
    <%end%>

    <%if can?(:read, Employee)%>
    <div class="col-md-3 col-sm-6 hero-feature">
        <div class="thumbnail">
            <h2>Employee Directory</h2>
            <div class="caption">
                <h3>Get employee detail</h3>
                <p>
                    <%= link_to "List", employees_path(), class: "btn btn-primary"%>
                </p>
            </div>
        </div>
    </div> 
    <%end%>
    
</div>

app/views/home/index.html.erb
<!-- Page Content -->
    

    <!-- Jumbotron Header -->
    <header class="jumbotron hero-spacer">
        <h1>A Warm Welcome!</h1>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsa, ipsam, eligendi, in quo sunt possimus non incidunt odit vero aliquid similique quaerat nam nobis illo aspernatur vitae fugiat numquam repellat.</p>
        <p><a class="btn btn-primary btn-large">Call to action!</a>
        </p>
    </header>

    <hr>

    <!-- Page Features -->
    <%= render partial: "admin_dashboard"%>

    <!-- /.row -->

    <!-- /.container -->