config/routes.rb
Rails.application.routes.draw do  
  resources :dimensions
  resources :goals
  resources :message_categories
  resources :messages, except: [:index, :destroy] do
    collection do
      get :sent_messages
      get :received_messages
    end
  end

  resources :posts
  devise_for :users, :controllers => {sessions: 'sessions', registrations: 'registrations'} 
  resources :employees do
    resources :dimensions
    resources :goals
    collection do
      post :search
      get :my_profile
    end
    member do 
      get :linked_in_profile
    end
    resources :users, only: [:new, :create, :edit, :update, :destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :job_titles
  resources :roles, only: [:index] do
    resources :dimensions
  end
  resources :companies do 
    resources :dimensions
    resources :goals
    resources :business_units do      
      resources :departments do
        resources :teams
      end
    end
  end

  resources :business_units do
    resources :dimensions
  end

  resources :teams do
    resources :dimensions
    resources :goals
  end

  resources :chat_rooms do
    member do
      delete :leave
    end
    # resources :chat_room_members, path: :members
    resources :chat_messages do
      collection do
        delete :clear_chat_history, to: "chat_messages#clear_chat_history"
      end
    end
  end


  mount ActionCable.server => '/cable'

  
  root to: "home#index"

  get '/api' => redirect('/swagger/dist/index.html?url=/apidocs/api-docs.json')

end

app/models/job_title.rb
class JobTitle < ApplicationRecord
	has_one :employee
	validates :title, :uniqueness => true
end

app/controllers/job_titles_controller.rb
class JobTitlesController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  # GET /job_titles
  # GET /job_titles.json
  def index
    @job_titles = JobTitle.all
  end

  # GET /job_titles/1
  # GET /job_titles/1.json
  def show
  end

  # GET /job_titles/new
  def new
    @job_title = JobTitle.new
  end

  # GET /job_titles/1/edit
  def edit
  end

  # POST /job_titles
  # POST /job_titles.json
  def create
    @job_title = JobTitle.new(job_title_params)

    respond_to do |format|
      if @job_title.save
        format.html { redirect_to @job_title, notice: 'Job title was successfully created.' }
        format.json { render :show, status: :created, location: @job_title }
      else
        format.html { render :new }
        format.json { render json: @job_title.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /job_titles/1
  # PATCH/PUT /job_titles/1.json
  def update
    respond_to do |format|
      if @job_title.update(job_title_params)
        format.html { redirect_to @job_title, notice: 'Job title was successfully updated.' }
        format.json { render :show, status: :ok, location: @job_title }
      else
        format.html { render :edit }
        format.json { render json: @job_title.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /job_titles/1
  # DELETE /job_titles/1.json
  def destroy
    @job_title.destroy
    respond_to do |format|
      format.html { redirect_to job_titles_url, notice: 'Job title was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    # Never trust parameters from the scary internet, only allow the white list through.
    def job_title_params
      params.require(:job_title).permit(:title, :description)
    end
end

app/helpers/job_titles_helper.rb
module JobTitlesHelper
end

app/views/job_titles/_form.html.erb
<%= form_for(job_title) do |f| %>
  <% if job_title.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(job_title.errors.count, "error") %> prohibited this job_title from being saved:</h2>

      <ul>
      <% job_title.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="col-md-12 col-sm-12 col-xs-12">

    <div class="form-group">
      <label class="col-lg-4 control-label">Title<span class="required">*</span></label>
      <div class="col-lg-6">
        <%= f.text_field :title, :class => 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <label class="col-lg-4 control-label">More information<span class="required">*</span></label>
      <div class="col-lg-6">
        <%= f.text_field :description, :class => 'form-control' %>
      </div>
    </div>
    

  </div>
  <div class="clearfix"></div>

  <div class="ln_solid"></div>

  <div class="form-group">

    <div class="col-md-3 col-sm-0 col-xs-2 col-md-offset-0 pull-right">
        <%= button_tag(:type => "submit", :class => "btn btn-success") do %>
          <span class="fa fa-save fa-fw"></span> Save
        <% end %>

        <%= link_to job_titles_path(), :class => 'btn btn-danger'  do %>
        <span class="fa fa-ban fa-fw"></span> Cancel
      <% end %>         
      </div>
    </div>
<% end %>

app/views/job_titles/edit.html.erb
<h1>Editing Job Title</h1>

<%= render 'form', job_title: @job_title %>

<%= link_to 'Show', @job_title %> |
<%= link_to 'Back', job_titles_path %>

app/views/job_titles/index.html.erb
<div class="row">
  <div class="col-md-12 col-sm-6 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2>Job Titles <small> </small></h2>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">

        <table class="table">
          <thead>
            <tr>
              <th>#</th>
              <th>Title</th>
              <th>Description</th>
              <th></th>  
            </tr>
          </thead>
          <tbody>
            <% @job_titles.each_with_index do |job_title, index| %>
              <tr>
                <td><%= index + 1%> </td>
                <td>
                  <%= job_title.title%>
                </td>
                <td>
                  <%= job_title.description%>
                </td>               
                <td><%= link_to 'Edit', edit_job_title_path(job_title) %></td>
                <td><%= link_to 'Destroy', job_title, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>                        
          </tbody>
        </table>

      </div>
    </div>
  </div>
  <%= link_to "Add New Job Title", new_job_title_path(), class: "btn btn-primary pull-right"%>
</div>

app/views/job_titles/new.html.erb
<h1>New Job Title</h1>

<%= render 'form', job_title: @job_title %>

<%= link_to 'Back', job_titles_path %>

app/views/job_titles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @job_title.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @job_title.description %>
</p>

<%= link_to 'Edit', edit_job_title_path(@job_title) %> |
<%= link_to 'Back', job_titles_path %>