config/routes.rb
Rails.application.routes.draw do  
  resources :dimensions
  resources :goals
  resources :message_categories
  resources :messages, except: [:index, :destroy] do
    collection do
      get :sent_messages
      get :received_messages
    end
  end

  resources :posts
  devise_for :users, :controllers => {sessions: 'sessions', registrations: 'registrations'} 
  resources :employees do
    resources :dimensions
    resources :goals
    collection do
      post :search
      get :my_profile
    end
    member do 
      get :linked_in_profile
    end
    resources :users, only: [:new, :create, :edit, :update, :destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :job_titles
  resources :roles, only: [:index] do
    resources :dimensions
  end
  resources :companies do 
    resources :dimensions
    resources :goals
    resources :business_units do      
      resources :departments do
        resources :teams
      end
    end
  end

  resources :business_units do
    resources :dimensions
  end

  resources :teams do
    resources :dimensions
    resources :goals
  end

  resources :chat_rooms do
    member do
      delete :leave
    end
    # resources :chat_room_members, path: :members
    resources :chat_messages do
      collection do
        delete :clear_chat_history, to: "chat_messages#clear_chat_history"
      end
    end
  end


  mount ActionCable.server => '/cable'

  
  root to: "home#index"

  get '/api' => redirect('/swagger/dist/index.html?url=/apidocs/api-docs.json')

end

app/models/business_unit.rb
# Business Unit Model
class BusinessUnit < ApplicationRecord
  belongs_to :company
  has_many :departments
  has_many :employees
  has_many :dimensions, as: :reference

  validates :title, uniqueness: :true
  validates :address_line_1, :city, :country, :phone, :fax, presence: true
  def address
    [
      address_line_1.try(:capitalize),
      address_line_2.try(:capitalize),
      city.try(:capitalize),
      state.try(:capitalize),
      zipcode.try(:capitalize)
    ].reject { |n| n.blank? }.join(', ')
  end
end

app/controllers/business_units_controller.rb
class BusinessUnitsController < ApplicationController
  before_action :authenticate_user!

  load_and_authorize_resource :company
  load_and_authorize_resource :business_unit, :through => :company

  before_action :set_breadcrumb

  # swagger_controller :business_unit, "business_unit Management"

  # swagger_api :create do
  #   summary "Creates a new Business Unit"
  #   param :form, "business_unit[title]", :string, :required, "Title"
  #   param :form, "business_unit[is_headquater]", :boolean, :optional, "Is Headquater"
  #   param :form, "business_unit[address_line_1]", :string, :required, "Address Line one"
  #   param :form, "business_unit[address_line_2]", :string, :optional, "Address Line one"
  #   param :form, "business_unit[city]", :string, :required, "City"
  #   param :form, "business_unit[state]", :string, :optional, "State"
  #   param :form, "business_unit[zipcode]", :string, :optional, "Zipcode"
  #   param :form, "business_unit[country]", :string, :required, "Country"
  #   param :form, "business_unit[phone]", :string, :optional, "Phone"   
  #   param :form, "business_unit[fax]", :string, :optional, "Fax"   
  #   param :form, "business_unit[url]", :string, :optional, "Url"

  #   response :unauthorized
  #   response :not_acceptable
  # end
  
  # swagger_api :update do
  #   param :form, "business_unit[title]", :string, :required, "Title"
  #   param :form, "business_unit[is_headquater]", :boolean, :optional, "Is Headquater"
  #   param :form, "business_unit[address_line_1]", :string, :required, "Address Line one"
  #   param :form, "business_unit[address_line_2]", :string, :optional, "Address Line one"
  #   param :form, "business_unit[city]", :string, :required, "City"
  #   param :form, "business_unit[state]", :string, :optional, "State"
  #   param :form, "business_unit[zipcode]", :string, :optional, "Zipcode"
  #   param :form, "business_unit[country]", :string, :required, "Country"
  #   param :form, "business_unit[phone]", :string, :optional, "Phone"   
  #   param :form, "business_unit[fax]", :string, :optional, "Fax"   
  #   param :form, "business_unit[url]", :string, :optional, "Url"

  #   response :unauthorized
  #   response :not_acceptable
  # end

  # GET /business_units
  # GET /business_units.json
  def index
    add_breadcrumb "Business Units", company_business_units_path(@company)
    # @business_units = @company.business_units
  end

  # GET /business_units/1
  # GET /business_units/1.json
  def show
  end

  # GET /business_units/new
  def new
    add_breadcrumb "Business Units", company_business_units_path(@company)
    add_breadcrumb "New Business Units"
  end

  # GET /business_units/1/edit
  def edit
    add_breadcrumb "Business Units", company_business_units_path(@company)
    add_breadcrumb "Edit Business Units"
  end

  # POST /business_units
  # POST /business_units.json
  def create
    @business_unit = @company.business_units.build(business_unit_params)
    # @business_unit = BusinessUnit.new(business_unit_params)

    respond_to do |format|
      if @business_unit.save
        format.html { redirect_to new_company_business_unit_department_path(@company, @business_unit), notice: 'Business unit was successfully created.' }
        format.json { render :show, status: :created, location: business_unit_params }
      else
        format.html { render :new }
        format.json { render json: @business_unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /business_units/1
  # PATCH/PUT /business_units/1.json
  def update
    respond_to do |format|
      if @business_unit.update(business_unit_params)
        format.html { redirect_to company_business_unit_departments_path(@company, @business_unit), notice: 'Business unit was successfully updated.' }
        format.json { render :show, status: :ok, location: business_unit_params }
      else
        format.html { render :edit }
        format.json { render json: @business_unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /business_units/1
  # DELETE /business_units/1.json
  def destroy
    @business_unit.destroy
    respond_to do |format|
      format.html { redirect_to business_units_url, notice: 'Business unit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_breadcrumb
      add_breadcrumb @company.name, company_path(@company)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def business_unit_params
      params.fetch(:business_unit, {}).permit(:title, :is_headquater, :address_line_1, :address_line_2, :city, :state, :zipcode, :country, :phone, :fax, :url, :company_id)
    end
end

app/helpers/business_units_helper.rb
module BusinessUnitsHelper
end

app/views/business_units/_form.html.erb
<%= form_for [company, business_unit] do |f| %>
  <% if business_unit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(business_unit.errors.count, "error") %> prohibited this business_unit from being saved:</h2>

      <ul>
      <% business_unit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="col-md-12 col-sm-12 col-xs-12">

    <div class="form-group">
      <label class="col-lg-4 control-label">Title<span class="required">*</span></label>
      <div class="col-lg-6">
        <%= f.text_field :title, :class => 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label "Is Headquater", :class => 'col-lg-4 control-label' %>
      <div class="col-lg-6">
        <div class="checkbox">
          <label>
            <%= f.check_box :is_headquater, {}%>
          </label>
        </div>
      </div>
    </div>

    <div class="form-group">
      <label class="col-lg-4 control-label">Address Line 2<span class="required">*</span></label>
      <div class="col-lg-6">
        <%= f.text_field :address_line_1, :class => 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label "Address Line 2", :class => 'col-lg-4 control-label' %>
      <div class="col-lg-6">
        <%= f.text_field :address_line_2, :class => 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label "City", :class => 'col-lg-4 control-label' %>
      <div class="col-lg-6">
        <%= f.text_field :city, :class => 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label "State", :class => 'col-lg-4 control-label' %>
      <div class="col-lg-6">
        <%= f.text_field :state, :class => 'form-control' %>
      </div>
    </div>


    <div class="form-group">
      <%= f.label "Zip Code", :class => 'col-lg-4 control-label' %>
      <div class="col-lg-6">
        <%= f.text_field :zipcode, :class => 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label "Country", :class => 'col-lg-4 control-label' %>
      <div class="col-lg-6">
        <%= f.text_field :country, :class => 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label "Contact Number", :class => 'col-lg-4 control-label' %>
      <div class="col-lg-6">
        <%= f.text_field :phone, :class => 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label "Fax", :class => 'col-lg-4 control-label' %>
      <div class="col-lg-6">
        <%= f.text_field :fax, :class => 'form-control', placeholder: "2 years & 5 months" %>
      </div>
    </div>
    
    <div class="form-group">
      <%= f.label "URL", :class => 'col-lg-4 control-label' %>
      <div class="col-lg-6">
        <%= f.text_field :url, :class => 'form-control' %>
      </div>
    </div>

  </div>
  <div class="clearfix"></div>

  <div class="ln_solid"></div>

  <div class="form-group">

    <div class="col-md-3 col-sm-0 col-xs-2 col-md-offset-0 pull-right">
        <%= button_tag(:type => "submit", :class => "btn btn-success") do %>
          <span class="fa fa-save fa-fw"></span> Save
        <% end %>

        <%= link_to root_path(), :class => 'btn btn-danger'  do %>
        <span class="fa fa-ban fa-fw"></span> Cancel
      <% end %>         
      </div>
    </div>

<% end %>

app/views/business_units/edit.html.erb
<h1>Editing Business Unit : <%= @business_unit.title%></h1>

<%= render partial: 'form', locals: {company: @company ,business_unit: @business_unit} %>

<%= link_to 'Back', company_business_units_path(@company) %>

app/views/business_units/index.html.erb
<div class="row">
  <div class="col-md-12 col-sm-6 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2>Business Units<small> of <%= @company.name%></small></h2>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">

                    <table class="table">
                      <thead>
                        <tr>
                          <th>#</th>
                          <th>Name</th>
                          <th>Address</th>
                          <th>URL</th>
                          <th></th>  
                        </tr>
                      </thead>
                      <tbody>
                        <% @business_units.each_with_index do |business_unit, index| %>
                          <tr>
                            <td><%= index + 1%> </td>
                            <td>
                              <%= business_unit.title%>
                            </td>
                            <td>
                              <%= business_unit.address%>
                            </td>
                            <td>
                              <%= link_to business_unit.url%>
                            </td>
                            <td><%= link_to 'Edit', edit_company_business_unit_path(@company, business_unit) %></td>
                            <td><%= link_to 'Destroy', company_business_unit_path(@company, business_unit), method: :delete, data: { confirm: 'Are you sure?' } %></td>
                            <td><%= link_to 'Departments', company_business_unit_departments_path(@company, business_unit) %></td>

                          </tr>
                        <% end %>                        
                      </tbody>
                    </table>

                  </div>
                </div>
              </div>

              <%= link_to "Add New Business Unit", new_company_business_unit_path(@company), class: "btn btn-primary pull-right"%>
</div>

app/views/business_units/new.html.erb
<h1>New Business Unit</h1>

<%= render partial: 'form', locals: {company: @company ,business_unit: @business_unit} %>

<%= link_to 'Back', edit_company_path(@company) %>

app/views/business_units/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_business_unit_path(@business_unit) %> |
<%= link_to 'Back', business_units_path %>